# See the configuration reference at https://github.com/scheb/2fa/blob/master/doc/configuration.md
scheb_two_factor:
    backup_codes:
        enabled: true
        manager: App\Security\TwoFactorAuthManager

    totp:
        enabled: true
        server_name: '%env(APP_HOSTNAME)%'
        issuer: Packagist
        window: 1

    trusted_device:
        enabled: true
        lifetime: 2592000 # 30 days
