#hwi_oauth_connect:
#    resource: '@HWIOAuthBundle/Resources/config/routing/connect.xml'
#    prefix:   /connect
#
## overrides the fosub /login page
#hwi_oauth_login:
#    resource: '@HWIOAuthBundle/Resources/config/routing/login.xml'
#    prefix:   /login
#
#hwi_oauth_redirect:
#    resource: '@HWIOAuthBundle/Resources/config/routing/redirect.xml'
#    prefix:   /login
#
github_check:
    path: /login/check-github

logout:
    path: /logout
