searchableAttributes:
    - "name"
    - "package_name"
    - "package_organisation"
    - "description"
    - "tags"

ranking:
    - "typo"
    - "geo"
    - "words"
    - "filters"
    - "attribute"
    - "proximity"
    - "exact"
    - "custom"

customRanking:
    - "desc(popularity)"

attributesToHighlight:
    - "name"
    - "package_name"
    - "package_organisation"
    - "description"

ignorePlurals: true
advancedSyntax: true
separatorsToIndex:
    - '/'

attributesForFaceting:
    - "type"
    - "tags"
